name: update clash-meta.yaml

on:
  push:
    paths-ignore:
      - "README.md"
      - "script/**"
      - "source/**"
      - ".gitignore"
    branches:
      - main
  schedule:
    - cron: '0 23 * * *'

jobs:
  Build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Update Clash
        run: |
          wget -O source/clash-meta.yaml ${{ secrets.CLASH_API }}
          rand=$(date +%s%N | md5sum |cut -c 1-5)
          sed -i "s/${{ secrets.CLASH_REPLACE }}/$rand/g" source/clash-meta.yaml

      - name: Commit files
        run: |
          git config --local user.email "snakem982@gmail.com"
          git config --local user.name "snakem982"
          git add .
          git commit -a -m "update clash-meta.yaml"

      - name: Git Push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          
